//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiedaPL_BusAPI_Test.AuctionHouse {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auction", Namespace="http://schemas.datacontract.org/2004/07/BiedaPL_BusAPI.Entities")]
    [System.SerializableAttribute()]
    public partial class Auction : BiedaPL_BusAPI_Test.AuctionHouse.AuctionDraft {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BiedaPL_BusAPI_Test.AuctionHouse.Bid[] BidsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BiedaPL_BusAPI_Test.AuctionHouse.AuctionClosure ClosureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTimeOffset TimeToEndField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiedaPL_BusAPI_Test.AuctionHouse.Bid[] Bids {
            get {
                return this.BidsField;
            }
            set {
                if ((object.ReferenceEquals(this.BidsField, value) != true)) {
                    this.BidsField = value;
                    this.RaisePropertyChanged("Bids");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiedaPL_BusAPI_Test.AuctionHouse.AuctionClosure Closure {
            get {
                return this.ClosureField;
            }
            set {
                if ((object.ReferenceEquals(this.ClosureField, value) != true)) {
                    this.ClosureField = value;
                    this.RaisePropertyChanged("Closure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset TimeToEnd {
            get {
                return this.TimeToEndField;
            }
            set {
                if ((this.TimeToEndField.Equals(value) != true)) {
                    this.TimeToEndField = value;
                    this.RaisePropertyChanged("TimeToEnd");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuctionDraft", Namespace="http://schemas.datacontract.org/2004/07/BiedaPL_BusAPI.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BiedaPL_BusAPI_Test.AuctionHouse.Auction))]
    public partial class AuctionDraft : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BiedaPL_BusAPI_Test.AuctionHouse.PricePerDelivery DeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BiedaPL_BusAPI_Test.AuctionHouse.AuctionItem ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BiedaPL_BusAPI_Test.AuctionHouse.User OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BiedaPL_BusAPI_Test.AuctionHouse.PricePerUnit PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiedaPL_BusAPI_Test.AuctionHouse.PricePerDelivery Delivery {
            get {
                return this.DeliveryField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryField, value) != true)) {
                    this.DeliveryField = value;
                    this.RaisePropertyChanged("Delivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiedaPL_BusAPI_Test.AuctionHouse.AuctionItem Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiedaPL_BusAPI_Test.AuctionHouse.User Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiedaPL_BusAPI_Test.AuctionHouse.PricePerUnit Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PricePerDelivery", Namespace="http://schemas.datacontract.org/2004/07/BiedaPL_BusAPI.Entities")]
    [System.SerializableAttribute()]
    public partial class PricePerDelivery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliverByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliverBy {
            get {
                return this.DeliverByField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliverByField, value) != true)) {
                    this.DeliverByField = value;
                    this.RaisePropertyChanged("DeliverBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuctionItem", Namespace="http://schemas.datacontract.org/2004/07/BiedaPL_BusAPI.Entities")]
    [System.SerializableAttribute()]
    public partial class AuctionItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PhotoLinkListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PhotoLinkList {
            get {
                return this.PhotoLinkListField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoLinkListField, value) != true)) {
                    this.PhotoLinkListField = value;
                    this.RaisePropertyChanged("PhotoLinkList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitType {
            get {
                return this.UnitTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitTypeField, value) != true)) {
                    this.UnitTypeField = value;
                    this.RaisePropertyChanged("UnitType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/BiedaPL_BusAPI.Entities")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PricePerUnit", Namespace="http://schemas.datacontract.org/2004/07/BiedaPL_BusAPI.Entities")]
    [System.SerializableAttribute()]
    public partial class PricePerUnit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuctionClosure", Namespace="http://schemas.datacontract.org/2004/07/BiedaPL_BusAPI.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class AuctionClosure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BiedaPL_BusAPI_Test.AuctionHouse.Auction AuctionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BiedaPL_BusAPI_Test.AuctionHouse.Bid OfferField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiedaPL_BusAPI_Test.AuctionHouse.Auction Auction {
            get {
                return this.AuctionField;
            }
            set {
                if ((object.ReferenceEquals(this.AuctionField, value) != true)) {
                    this.AuctionField = value;
                    this.RaisePropertyChanged("Auction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiedaPL_BusAPI_Test.AuctionHouse.Bid Offer {
            get {
                return this.OfferField;
            }
            set {
                if ((object.ReferenceEquals(this.OfferField, value) != true)) {
                    this.OfferField = value;
                    this.RaisePropertyChanged("Offer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bid", Namespace="http://schemas.datacontract.org/2004/07/BiedaPL_BusAPI.Entities")]
    [System.SerializableAttribute()]
    public partial class Bid : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BiedaPL_BusAPI_Test.AuctionHouse.User OfferentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTimeOffset TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BiedaPL_BusAPI_Test.AuctionHouse.User Offerent {
            get {
                return this.OfferentField;
            }
            set {
                if ((object.ReferenceEquals(this.OfferentField, value) != true)) {
                    this.OfferentField = value;
                    this.RaisePropertyChanged("Offerent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuctionHouse.IAuctionManager")]
    public interface IAuctionManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionManager/getCategoryList", ReplyAction="http://tempuri.org/IAuctionManager/getCategoryListResponse")]
        string[] getCategoryList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionManager/getAuctionList", ReplyAction="http://tempuri.org/IAuctionManager/getAuctionListResponse")]
        BiedaPL_BusAPI_Test.AuctionHouse.Auction[] getAuctionList(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionManager/doCreateAuction", ReplyAction="http://tempuri.org/IAuctionManager/doCreateAuctionResponse")]
        BiedaPL_BusAPI_Test.AuctionHouse.Auction doCreateAuction(BiedaPL_BusAPI_Test.AuctionHouse.User user, BiedaPL_BusAPI_Test.AuctionHouse.Auction auction, string categoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionManager/doCloneAuction", ReplyAction="http://tempuri.org/IAuctionManager/doCloneAuctionResponse")]
        BiedaPL_BusAPI_Test.AuctionHouse.Auction doCloneAuction(BiedaPL_BusAPI_Test.AuctionHouse.User user, BiedaPL_BusAPI_Test.AuctionHouse.Auction auction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionManager/doFindAuction", ReplyAction="http://tempuri.org/IAuctionManager/doFindAuctionResponse")]
        BiedaPL_BusAPI_Test.AuctionHouse.Auction doFindAuction(BiedaPL_BusAPI_Test.AuctionHouse.Auction auction);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAuctionManager/doBid")]
        void doBid(BiedaPL_BusAPI_Test.AuctionHouse.User user, BiedaPL_BusAPI_Test.AuctionHouse.Auction auction, decimal pricePerUnit, int amount);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAuctionManager/doCloseAuction")]
        void doCloseAuction(BiedaPL_BusAPI_Test.AuctionHouse.User user, BiedaPL_BusAPI_Test.AuctionHouse.Auction auction, string comment);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAuctionManager/doComment")]
        void doComment(BiedaPL_BusAPI_Test.AuctionHouse.User user, string comment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuctionManagerChannel : BiedaPL_BusAPI_Test.AuctionHouse.IAuctionManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuctionManagerClient : System.ServiceModel.ClientBase<BiedaPL_BusAPI_Test.AuctionHouse.IAuctionManager>, BiedaPL_BusAPI_Test.AuctionHouse.IAuctionManager {
        
        public AuctionManagerClient() {
        }
        
        public AuctionManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuctionManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuctionManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuctionManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getCategoryList() {
            return base.Channel.getCategoryList();
        }
        
        public BiedaPL_BusAPI_Test.AuctionHouse.Auction[] getAuctionList(string category) {
            return base.Channel.getAuctionList(category);
        }
        
        public BiedaPL_BusAPI_Test.AuctionHouse.Auction doCreateAuction(BiedaPL_BusAPI_Test.AuctionHouse.User user, BiedaPL_BusAPI_Test.AuctionHouse.Auction auction, string categoryName) {
            return base.Channel.doCreateAuction(user, auction, categoryName);
        }
        
        public BiedaPL_BusAPI_Test.AuctionHouse.Auction doCloneAuction(BiedaPL_BusAPI_Test.AuctionHouse.User user, BiedaPL_BusAPI_Test.AuctionHouse.Auction auction) {
            return base.Channel.doCloneAuction(user, auction);
        }
        
        public BiedaPL_BusAPI_Test.AuctionHouse.Auction doFindAuction(BiedaPL_BusAPI_Test.AuctionHouse.Auction auction) {
            return base.Channel.doFindAuction(auction);
        }
        
        public void doBid(BiedaPL_BusAPI_Test.AuctionHouse.User user, BiedaPL_BusAPI_Test.AuctionHouse.Auction auction, decimal pricePerUnit, int amount) {
            base.Channel.doBid(user, auction, pricePerUnit, amount);
        }
        
        public void doCloseAuction(BiedaPL_BusAPI_Test.AuctionHouse.User user, BiedaPL_BusAPI_Test.AuctionHouse.Auction auction, string comment) {
            base.Channel.doCloseAuction(user, auction, comment);
        }
        
        public void doComment(BiedaPL_BusAPI_Test.AuctionHouse.User user, string comment) {
            base.Channel.doComment(user, comment);
        }
    }
}
