//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.5420
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBiedaService")]
public interface IBiedaService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/GetMessage", ReplyAction="http://tempuri.org/IBiedaService/GetMessageResponse")]
    string GetMessage(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/GetMessage2", ReplyAction="http://tempuri.org/IBiedaService/GetMessage2Response")]
    string GetMessage2(string user, string pass);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/RegisterUser", ReplyAction="http://tempuri.org/IBiedaService/RegisterUserResponse")]
    string RegisterUser(string login, string haslo, string imie, string nazwisko, string email, string telefon, string kraj, string miasto, string kod, string ulica, string dom, string mieszkanie);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IBiedaServiceChannel : IBiedaService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class BiedaServiceClient : System.ServiceModel.ClientBase<IBiedaService>, IBiedaService
{
    
    public BiedaServiceClient()
    {
    }
    
    public BiedaServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BiedaServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BiedaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BiedaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetMessage(string name)
    {
        return base.Channel.GetMessage(name);
    }
    
    public string GetMessage2(string user, string pass)
    {
        return base.Channel.GetMessage2(user, pass);
    }
    
    public string RegisterUser(string login, string haslo, string imie, string nazwisko, string email, string telefon, string kraj, string miasto, string kod, string ulica, string dom, string mieszkanie)
    {
        return base.Channel.RegisterUser(login, haslo, imie, nazwisko, email, telefon, kraj, miasto, kod, ulica, dom, mieszkanie);
    }
}
