//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.5420
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBiedaService")]
public interface IBiedaService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/RegisterUser", ReplyAction="http://tempuri.org/IBiedaService/RegisterUserResponse")]
    string RegisterUser(string login, string haslo, string imie, string nazwisko, string email, string telefon, string kraj, string miasto, string kod, string ulica, string dom, string mieszkanie);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/getAuctionInfo", ReplyAction="http://tempuri.org/IBiedaService/getAuctionInfoResponse")]
    string[] getAuctionInfo(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/isAuctionOver", ReplyAction="http://tempuri.org/IBiedaService/isAuctionOverResponse")]
    bool isAuctionOver(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/CheckRegex", ReplyAction="http://tempuri.org/IBiedaService/CheckRegexResponse")]
    string CheckRegex(string klucz, string wartosc);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/LoginIn", ReplyAction="http://tempuri.org/IBiedaService/LoginInResponse")]
    string LoginIn(string login, string pass);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/IsSeller", ReplyAction="http://tempuri.org/IBiedaService/IsSellerResponse")]
    string IsSeller(string login);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/ChangePass", ReplyAction="http://tempuri.org/IBiedaService/ChangePassResponse")]
    string ChangePass(string login, string newPass);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/UpgradeAcc", ReplyAction="http://tempuri.org/IBiedaService/UpgradeAccResponse")]
    string UpgradeAcc(string login, string numerKonta);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/EditBankAccount", ReplyAction="http://tempuri.org/IBiedaService/EditBankAccountResponse")]
    string EditBankAccount(string login, string numerKonta);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/DeleteAcc", ReplyAction="http://tempuri.org/IBiedaService/DeleteAccResponse")]
    string DeleteAcc(string login);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/LoadAccInfo", ReplyAction="http://tempuri.org/IBiedaService/LoadAccInfoResponse")]
    string[] LoadAccInfo(string login);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/ChangeUserInfo", ReplyAction="http://tempuri.org/IBiedaService/ChangeUserInfoResponse")]
    string ChangeUserInfo(string login, string imie, string nazwisko, string email, string telefon, string kraj, string miasto, string kod, string ulica, string dom, string mieszkanie);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/getMessages", ReplyAction="http://tempuri.org/IBiedaService/getMessagesResponse")]
    string[] getMessages(string login);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/getAuctionWinner", ReplyAction="http://tempuri.org/IBiedaService/getAuctionWinnerResponse")]
    string getAuctionWinner(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/getAuctionHighestOffer", ReplyAction="http://tempuri.org/IBiedaService/getAuctionHighestOfferResponse")]
    string getAuctionHighestOffer(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/AuctionAllreadyCommented", ReplyAction="http://tempuri.org/IBiedaService/AuctionAllreadyCommentedResponse")]
    bool AuctionAllreadyCommented(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiedaService/addComment", ReplyAction="http://tempuri.org/IBiedaService/addCommentResponse")]
    bool addComment(int id_aukcji, string login, string comment, int ocena);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IBiedaServiceChannel : IBiedaService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class BiedaServiceClient : System.ServiceModel.ClientBase<IBiedaService>, IBiedaService
{
    
    public BiedaServiceClient()
    {
    }
    
    public BiedaServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BiedaServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BiedaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BiedaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string RegisterUser(string login, string haslo, string imie, string nazwisko, string email, string telefon, string kraj, string miasto, string kod, string ulica, string dom, string mieszkanie)
    {
        return base.Channel.RegisterUser(login, haslo, imie, nazwisko, email, telefon, kraj, miasto, kod, ulica, dom, mieszkanie);
    }
    
    public string[] getAuctionInfo(int id)
    {
        return base.Channel.getAuctionInfo(id);
    }
    
    public bool isAuctionOver(int id)
    {
        return base.Channel.isAuctionOver(id);
    }
    
    public string CheckRegex(string klucz, string wartosc)
    {
        return base.Channel.CheckRegex(klucz, wartosc);
    }
    
    public string LoginIn(string login, string pass)
    {
        return base.Channel.LoginIn(login, pass);
    }
    
    public string IsSeller(string login)
    {
        return base.Channel.IsSeller(login);
    }
    
    public string ChangePass(string login, string newPass)
    {
        return base.Channel.ChangePass(login, newPass);
    }
    
    public string UpgradeAcc(string login, string numerKonta)
    {
        return base.Channel.UpgradeAcc(login, numerKonta);
    }
    
    public string EditBankAccount(string login, string numerKonta)
    {
        return base.Channel.EditBankAccount(login, numerKonta);
    }
    
    public string DeleteAcc(string login)
    {
        return base.Channel.DeleteAcc(login);
    }
    
    public string[] LoadAccInfo(string login)
    {
        return base.Channel.LoadAccInfo(login);
    }
    
    public string ChangeUserInfo(string login, string imie, string nazwisko, string email, string telefon, string kraj, string miasto, string kod, string ulica, string dom, string mieszkanie)
    {
        return base.Channel.ChangeUserInfo(login, imie, nazwisko, email, telefon, kraj, miasto, kod, ulica, dom, mieszkanie);
    }
    
    public string[] getMessages(string login)
    {
        return base.Channel.getMessages(login);
    }
    
    public string getAuctionWinner(int id)
    {
        return base.Channel.getAuctionWinner(id);
    }
    
    public string getAuctionHighestOffer(int id)
    {
        return base.Channel.getAuctionHighestOffer(id);
    }
    
    public bool AuctionAllreadyCommented(int id)
    {
        return base.Channel.AuctionAllreadyCommented(id);
    }
    
    public bool addComment(int id_aukcji, string login, string comment, int ocena)
    {
        return base.Channel.addComment(id_aukcji, login, comment, ocena);
    }
}
