#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.18408
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiedaPL_BusAPI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSource")]
	public partial class DbAuctionHouseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAUKCJA(AUKCJA instance);
    partial void UpdateAUKCJA(AUKCJA instance);
    partial void DeleteAUKCJA(AUKCJA instance);
    partial void InsertZDJECIE(ZDJECIE instance);
    partial void UpdateZDJECIE(ZDJECIE instance);
    partial void DeleteZDJECIE(ZDJECIE instance);
    partial void InsertDANE(DANE instance);
    partial void UpdateDANE(DANE instance);
    partial void DeleteDANE(DANE instance);
    partial void InsertKATEGORIA(KATEGORIA instance);
    partial void UpdateKATEGORIA(KATEGORIA instance);
    partial void DeleteKATEGORIA(KATEGORIA instance);
    partial void InsertKLIENT(KLIENT instance);
    partial void UpdateKLIENT(KLIENT instance);
    partial void DeleteKLIENT(KLIENT instance);
    partial void InsertOFERTA(OFERTA instance);
    partial void UpdateOFERTA(OFERTA instance);
    partial void DeleteOFERTA(OFERTA instance);
    partial void InsertPOWIADOMIENIE(POWIADOMIENIE instance);
    partial void UpdatePOWIADOMIENIE(POWIADOMIENIE instance);
    partial void DeletePOWIADOMIENIE(POWIADOMIENIE instance);
    partial void InsertSPRZEDAWCA(SPRZEDAWCA instance);
    partial void UpdateSPRZEDAWCA(SPRZEDAWCA instance);
    partial void DeleteSPRZEDAWCA(SPRZEDAWCA instance);
    #endregion
		
		public DbAuctionHouseDataContext() : 
				base(global::BiedaPL_BusAPI.Properties.Settings.Default.DataSourceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbAuctionHouseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbAuctionHouseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbAuctionHouseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbAuctionHouseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AUKCJA> AUKCJAs
		{
			get
			{
				return this.GetTable<AUKCJA>();
			}
		}
		
		public System.Data.Linq.Table<ZDJECIE> ZDJECIEs
		{
			get
			{
				return this.GetTable<ZDJECIE>();
			}
		}
		
		public System.Data.Linq.Table<DANE> DANEs
		{
			get
			{
				return this.GetTable<DANE>();
			}
		}
		
		public System.Data.Linq.Table<KATEGORIA> KATEGORIAs
		{
			get
			{
				return this.GetTable<KATEGORIA>();
			}
		}
		
		public System.Data.Linq.Table<KLIENT> KLIENTs
		{
			get
			{
				return this.GetTable<KLIENT>();
			}
		}
		
		public System.Data.Linq.Table<OFERTA> OFERTAs
		{
			get
			{
				return this.GetTable<OFERTA>();
			}
		}
		
		public System.Data.Linq.Table<POWIADOMIENIE> POWIADOMIENIEs
		{
			get
			{
				return this.GetTable<POWIADOMIENIE>();
			}
		}
		
		public System.Data.Linq.Table<SPRZEDAWCA> SPRZEDAWCAs
		{
			get
			{
				return this.GetTable<SPRZEDAWCA>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DODAJ_AUKCJE")]
		public int DODAJ_AUKCJE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string kategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string login_uzytkownika, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dlugosc_trwania, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string opis, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nazwa_produktu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> cena_startowa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> cena_wysyłki)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), kategoria, login_uzytkownika, dlugosc_trwania, opis, nazwa_produktu, cena_startowa, cena_wysyłki);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AUKCJA")]
	public partial class AUKCJA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_aukcji;
		
		private int _id_kategoria;
		
		private string _login;
		
		private System.DateTime _data_zakonczenia;
		
		private string _opis;
		
		private string _nazwa_produktu;
		
		private decimal _cena_startowa;
		
		private decimal _cena_wysylki;
		
		private System.Nullable<int> _ocena_sprzedawcy;
		
		private string _komentarz_dla_sprzedawcy;
		
		private EntitySet<ZDJECIE> _ZDJECIEs;
		
		private EntitySet<OFERTA> _OFERTAs;
		
		private EntityRef<KATEGORIA> _KATEGORIA;
		
		private EntityRef<SPRZEDAWCA> _SPRZEDAWCA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_aukcjiChanging(int value);
    partial void Onid_aukcjiChanged();
    partial void Onid_kategoriaChanging(int value);
    partial void Onid_kategoriaChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void Ondata_zakonczeniaChanging(System.DateTime value);
    partial void Ondata_zakonczeniaChanged();
    partial void OnopisChanging(string value);
    partial void OnopisChanged();
    partial void Onnazwa_produktuChanging(string value);
    partial void Onnazwa_produktuChanged();
    partial void Oncena_startowaChanging(decimal value);
    partial void Oncena_startowaChanged();
    partial void Oncena_wysylkiChanging(decimal value);
    partial void Oncena_wysylkiChanged();
    partial void Onocena_sprzedawcyChanging(System.Nullable<int> value);
    partial void Onocena_sprzedawcyChanged();
    partial void Onkomentarz_dla_sprzedawcyChanging(string value);
    partial void Onkomentarz_dla_sprzedawcyChanged();
    #endregion
		
		public AUKCJA()
		{
			this._ZDJECIEs = new EntitySet<ZDJECIE>(new Action<ZDJECIE>(this.attach_ZDJECIEs), new Action<ZDJECIE>(this.detach_ZDJECIEs));
			this._OFERTAs = new EntitySet<OFERTA>(new Action<OFERTA>(this.attach_OFERTAs), new Action<OFERTA>(this.detach_OFERTAs));
			this._KATEGORIA = default(EntityRef<KATEGORIA>);
			this._SPRZEDAWCA = default(EntityRef<SPRZEDAWCA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_aukcji", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_aukcji
		{
			get
			{
				return this._id_aukcji;
			}
			set
			{
				if ((this._id_aukcji != value))
				{
					this.Onid_aukcjiChanging(value);
					this.SendPropertyChanging();
					this._id_aukcji = value;
					this.SendPropertyChanged("id_aukcji");
					this.Onid_aukcjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kategoria", DbType="Int NOT NULL")]
		public int id_kategoria
		{
			get
			{
				return this._id_kategoria;
			}
			set
			{
				if ((this._id_kategoria != value))
				{
					if (this._KATEGORIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_kategoriaChanging(value);
					this.SendPropertyChanging();
					this._id_kategoria = value;
					this.SendPropertyChanged("id_kategoria");
					this.Onid_kategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					if (this._SPRZEDAWCA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_zakonczenia", DbType="DateTime NOT NULL")]
		public System.DateTime data_zakonczenia
		{
			get
			{
				return this._data_zakonczenia;
			}
			set
			{
				if ((this._data_zakonczenia != value))
				{
					this.Ondata_zakonczeniaChanging(value);
					this.SendPropertyChanging();
					this._data_zakonczenia = value;
					this.SendPropertyChanged("data_zakonczenia");
					this.Ondata_zakonczeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opis", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string opis
		{
			get
			{
				return this._opis;
			}
			set
			{
				if ((this._opis != value))
				{
					this.OnopisChanging(value);
					this.SendPropertyChanging();
					this._opis = value;
					this.SendPropertyChanged("opis");
					this.OnopisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa_produktu", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nazwa_produktu
		{
			get
			{
				return this._nazwa_produktu;
			}
			set
			{
				if ((this._nazwa_produktu != value))
				{
					this.Onnazwa_produktuChanging(value);
					this.SendPropertyChanging();
					this._nazwa_produktu = value;
					this.SendPropertyChanged("nazwa_produktu");
					this.Onnazwa_produktuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cena_startowa", DbType="Money NOT NULL")]
		public decimal cena_startowa
		{
			get
			{
				return this._cena_startowa;
			}
			set
			{
				if ((this._cena_startowa != value))
				{
					this.Oncena_startowaChanging(value);
					this.SendPropertyChanging();
					this._cena_startowa = value;
					this.SendPropertyChanged("cena_startowa");
					this.Oncena_startowaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cena_wysylki", DbType="Money NOT NULL")]
		public decimal cena_wysylki
		{
			get
			{
				return this._cena_wysylki;
			}
			set
			{
				if ((this._cena_wysylki != value))
				{
					this.Oncena_wysylkiChanging(value);
					this.SendPropertyChanging();
					this._cena_wysylki = value;
					this.SendPropertyChanged("cena_wysylki");
					this.Oncena_wysylkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ocena_sprzedawcy", DbType="Int")]
		public System.Nullable<int> ocena_sprzedawcy
		{
			get
			{
				return this._ocena_sprzedawcy;
			}
			set
			{
				if ((this._ocena_sprzedawcy != value))
				{
					this.Onocena_sprzedawcyChanging(value);
					this.SendPropertyChanging();
					this._ocena_sprzedawcy = value;
					this.SendPropertyChanged("ocena_sprzedawcy");
					this.Onocena_sprzedawcyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_komentarz_dla_sprzedawcy", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string komentarz_dla_sprzedawcy
		{
			get
			{
				return this._komentarz_dla_sprzedawcy;
			}
			set
			{
				if ((this._komentarz_dla_sprzedawcy != value))
				{
					this.Onkomentarz_dla_sprzedawcyChanging(value);
					this.SendPropertyChanging();
					this._komentarz_dla_sprzedawcy = value;
					this.SendPropertyChanged("komentarz_dla_sprzedawcy");
					this.Onkomentarz_dla_sprzedawcyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AUKCJA_ZDJECIE", Storage="_ZDJECIEs", ThisKey="id_aukcji", OtherKey="id_aukcji")]
		public EntitySet<ZDJECIE> ZDJECIEs
		{
			get
			{
				return this._ZDJECIEs;
			}
			set
			{
				this._ZDJECIEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AUKCJA_OFERTA", Storage="_OFERTAs", ThisKey="id_aukcji", OtherKey="id_aukcji")]
		public EntitySet<OFERTA> OFERTAs
		{
			get
			{
				return this._OFERTAs;
			}
			set
			{
				this._OFERTAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KATEGORIA_AUKCJA", Storage="_KATEGORIA", ThisKey="id_kategoria", OtherKey="id_kategoria", IsForeignKey=true)]
		public KATEGORIA KATEGORIA
		{
			get
			{
				return this._KATEGORIA.Entity;
			}
			set
			{
				KATEGORIA previousValue = this._KATEGORIA.Entity;
				if (((previousValue != value) 
							|| (this._KATEGORIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KATEGORIA.Entity = null;
						previousValue.AUKCJAs.Remove(this);
					}
					this._KATEGORIA.Entity = value;
					if ((value != null))
					{
						value.AUKCJAs.Add(this);
						this._id_kategoria = value.id_kategoria;
					}
					else
					{
						this._id_kategoria = default(int);
					}
					this.SendPropertyChanged("KATEGORIA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SPRZEDAWCA_AUKCJA", Storage="_SPRZEDAWCA", ThisKey="login", OtherKey="login", IsForeignKey=true)]
		public SPRZEDAWCA SPRZEDAWCA
		{
			get
			{
				return this._SPRZEDAWCA.Entity;
			}
			set
			{
				SPRZEDAWCA previousValue = this._SPRZEDAWCA.Entity;
				if (((previousValue != value) 
							|| (this._SPRZEDAWCA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SPRZEDAWCA.Entity = null;
						previousValue.AUKCJAs.Remove(this);
					}
					this._SPRZEDAWCA.Entity = value;
					if ((value != null))
					{
						value.AUKCJAs.Add(this);
						this._login = value.login;
					}
					else
					{
						this._login = default(string);
					}
					this.SendPropertyChanged("SPRZEDAWCA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ZDJECIEs(ZDJECIE entity)
		{
			this.SendPropertyChanging();
			entity.AUKCJA = this;
		}
		
		private void detach_ZDJECIEs(ZDJECIE entity)
		{
			this.SendPropertyChanging();
			entity.AUKCJA = null;
		}
		
		private void attach_OFERTAs(OFERTA entity)
		{
			this.SendPropertyChanging();
			entity.AUKCJA = this;
		}
		
		private void detach_OFERTAs(OFERTA entity)
		{
			this.SendPropertyChanging();
			entity.AUKCJA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ZDJECIE")]
	public partial class ZDJECIE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_zdjecia;
		
		private int _id_aukcji;
		
		private System.Data.Linq.Binary _zdjecie1;
		
		private string _podpis;
		
		private EntityRef<AUKCJA> _AUKCJA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_zdjeciaChanging(int value);
    partial void Onid_zdjeciaChanged();
    partial void Onid_aukcjiChanging(int value);
    partial void Onid_aukcjiChanged();
    partial void Onzdjecie1Changing(System.Data.Linq.Binary value);
    partial void Onzdjecie1Changed();
    partial void OnpodpisChanging(string value);
    partial void OnpodpisChanged();
    #endregion
		
		public ZDJECIE()
		{
			this._AUKCJA = default(EntityRef<AUKCJA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_zdjecia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_zdjecia
		{
			get
			{
				return this._id_zdjecia;
			}
			set
			{
				if ((this._id_zdjecia != value))
				{
					this.Onid_zdjeciaChanging(value);
					this.SendPropertyChanging();
					this._id_zdjecia = value;
					this.SendPropertyChanged("id_zdjecia");
					this.Onid_zdjeciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_aukcji", DbType="Int NOT NULL")]
		public int id_aukcji
		{
			get
			{
				return this._id_aukcji;
			}
			set
			{
				if ((this._id_aukcji != value))
				{
					if (this._AUKCJA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_aukcjiChanging(value);
					this.SendPropertyChanging();
					this._id_aukcji = value;
					this.SendPropertyChanged("id_aukcji");
					this.Onid_aukcjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="zdjecie", Storage="_zdjecie1", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary zdjecie1
		{
			get
			{
				return this._zdjecie1;
			}
			set
			{
				if ((this._zdjecie1 != value))
				{
					this.Onzdjecie1Changing(value);
					this.SendPropertyChanging();
					this._zdjecie1 = value;
					this.SendPropertyChanged("zdjecie1");
					this.Onzdjecie1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_podpis", DbType="VarChar(50)")]
		public string podpis
		{
			get
			{
				return this._podpis;
			}
			set
			{
				if ((this._podpis != value))
				{
					this.OnpodpisChanging(value);
					this.SendPropertyChanging();
					this._podpis = value;
					this.SendPropertyChanged("podpis");
					this.OnpodpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AUKCJA_ZDJECIE", Storage="_AUKCJA", ThisKey="id_aukcji", OtherKey="id_aukcji", IsForeignKey=true)]
		public AUKCJA AUKCJA
		{
			get
			{
				return this._AUKCJA.Entity;
			}
			set
			{
				AUKCJA previousValue = this._AUKCJA.Entity;
				if (((previousValue != value) 
							|| (this._AUKCJA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AUKCJA.Entity = null;
						previousValue.ZDJECIEs.Remove(this);
					}
					this._AUKCJA.Entity = value;
					if ((value != null))
					{
						value.ZDJECIEs.Add(this);
						this._id_aukcji = value.id_aukcji;
					}
					else
					{
						this._id_aukcji = default(int);
					}
					this.SendPropertyChanged("AUKCJA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANE")]
	public partial class DANE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_dane;
		
		private string _telefon;
		
		private string _email;
		
		private string _nr_konta;
		
		private string _kraj;
		
		private string _miasto;
		
		private string _kod;
		
		private string _ulica;
		
		private string _budynek;
		
		private string _mieszkanie;
		
		private string _imie;
		
		private string _nazwisko;
		
		private EntitySet<KLIENT> _KLIENTs;
		
		private EntitySet<SPRZEDAWCA> _SPRZEDAWCAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_daneChanging(int value);
    partial void Onid_daneChanged();
    partial void OntelefonChanging(string value);
    partial void OntelefonChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onnr_kontaChanging(string value);
    partial void Onnr_kontaChanged();
    partial void OnkrajChanging(string value);
    partial void OnkrajChanged();
    partial void OnmiastoChanging(string value);
    partial void OnmiastoChanged();
    partial void OnkodChanging(string value);
    partial void OnkodChanged();
    partial void OnulicaChanging(string value);
    partial void OnulicaChanged();
    partial void OnbudynekChanging(string value);
    partial void OnbudynekChanged();
    partial void OnmieszkanieChanging(string value);
    partial void OnmieszkanieChanged();
    partial void OnimieChanging(string value);
    partial void OnimieChanged();
    partial void OnnazwiskoChanging(string value);
    partial void OnnazwiskoChanged();
    #endregion
		
		public DANE()
		{
			this._KLIENTs = new EntitySet<KLIENT>(new Action<KLIENT>(this.attach_KLIENTs), new Action<KLIENT>(this.detach_KLIENTs));
			this._SPRZEDAWCAs = new EntitySet<SPRZEDAWCA>(new Action<SPRZEDAWCA>(this.attach_SPRZEDAWCAs), new Action<SPRZEDAWCA>(this.detach_SPRZEDAWCAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dane", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_dane
		{
			get
			{
				return this._id_dane;
			}
			set
			{
				if ((this._id_dane != value))
				{
					this.Onid_daneChanging(value);
					this.SendPropertyChanging();
					this._id_dane = value;
					this.SendPropertyChanged("id_dane");
					this.Onid_daneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this.OntelefonChanging(value);
					this.SendPropertyChanging();
					this._telefon = value;
					this.SendPropertyChanged("telefon");
					this.OntelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_konta", DbType="VarChar(26)")]
		public string nr_konta
		{
			get
			{
				return this._nr_konta;
			}
			set
			{
				if ((this._nr_konta != value))
				{
					this.Onnr_kontaChanging(value);
					this.SendPropertyChanging();
					this._nr_konta = value;
					this.SendPropertyChanged("nr_konta");
					this.Onnr_kontaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kraj", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string kraj
		{
			get
			{
				return this._kraj;
			}
			set
			{
				if ((this._kraj != value))
				{
					this.OnkrajChanging(value);
					this.SendPropertyChanging();
					this._kraj = value;
					this.SendPropertyChanged("kraj");
					this.OnkrajChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miasto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string miasto
		{
			get
			{
				return this._miasto;
			}
			set
			{
				if ((this._miasto != value))
				{
					this.OnmiastoChanging(value);
					this.SendPropertyChanging();
					this._miasto = value;
					this.SendPropertyChanged("miasto");
					this.OnmiastoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kod", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string kod
		{
			get
			{
				return this._kod;
			}
			set
			{
				if ((this._kod != value))
				{
					this.OnkodChanging(value);
					this.SendPropertyChanging();
					this._kod = value;
					this.SendPropertyChanged("kod");
					this.OnkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ulica", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ulica
		{
			get
			{
				return this._ulica;
			}
			set
			{
				if ((this._ulica != value))
				{
					this.OnulicaChanging(value);
					this.SendPropertyChanging();
					this._ulica = value;
					this.SendPropertyChanged("ulica");
					this.OnulicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_budynek", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string budynek
		{
			get
			{
				return this._budynek;
			}
			set
			{
				if ((this._budynek != value))
				{
					this.OnbudynekChanging(value);
					this.SendPropertyChanging();
					this._budynek = value;
					this.SendPropertyChanged("budynek");
					this.OnbudynekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mieszkanie", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string mieszkanie
		{
			get
			{
				return this._mieszkanie;
			}
			set
			{
				if ((this._mieszkanie != value))
				{
					this.OnmieszkanieChanging(value);
					this.SendPropertyChanging();
					this._mieszkanie = value;
					this.SendPropertyChanged("mieszkanie");
					this.OnmieszkanieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imie", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string imie
		{
			get
			{
				return this._imie;
			}
			set
			{
				if ((this._imie != value))
				{
					this.OnimieChanging(value);
					this.SendPropertyChanging();
					this._imie = value;
					this.SendPropertyChanged("imie");
					this.OnimieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwisko", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nazwisko
		{
			get
			{
				return this._nazwisko;
			}
			set
			{
				if ((this._nazwisko != value))
				{
					this.OnnazwiskoChanging(value);
					this.SendPropertyChanging();
					this._nazwisko = value;
					this.SendPropertyChanged("nazwisko");
					this.OnnazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANE_KLIENT", Storage="_KLIENTs", ThisKey="id_dane", OtherKey="id_dane")]
		public EntitySet<KLIENT> KLIENTs
		{
			get
			{
				return this._KLIENTs;
			}
			set
			{
				this._KLIENTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANE_SPRZEDAWCA", Storage="_SPRZEDAWCAs", ThisKey="id_dane", OtherKey="id_dane")]
		public EntitySet<SPRZEDAWCA> SPRZEDAWCAs
		{
			get
			{
				return this._SPRZEDAWCAs;
			}
			set
			{
				this._SPRZEDAWCAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KLIENTs(KLIENT entity)
		{
			this.SendPropertyChanging();
			entity.DANE = this;
		}
		
		private void detach_KLIENTs(KLIENT entity)
		{
			this.SendPropertyChanging();
			entity.DANE = null;
		}
		
		private void attach_SPRZEDAWCAs(SPRZEDAWCA entity)
		{
			this.SendPropertyChanging();
			entity.DANE = this;
		}
		
		private void detach_SPRZEDAWCAs(SPRZEDAWCA entity)
		{
			this.SendPropertyChanging();
			entity.DANE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KATEGORIA")]
	public partial class KATEGORIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_kategoria;
		
		private System.Nullable<int> _id_rodzica;
		
		private string _Nazwa;
		
		private System.Nullable<bool> _czy_lisc;
		
		private EntitySet<AUKCJA> _AUKCJAs;
		
		private EntitySet<KATEGORIA> _KATEGORIAs;
		
		private EntityRef<KATEGORIA> _KATEGORIA1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_kategoriaChanging(int value);
    partial void Onid_kategoriaChanged();
    partial void Onid_rodzicaChanging(System.Nullable<int> value);
    partial void Onid_rodzicaChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    partial void Onczy_liscChanging(System.Nullable<bool> value);
    partial void Onczy_liscChanged();
    #endregion
		
		public KATEGORIA()
		{
			this._AUKCJAs = new EntitySet<AUKCJA>(new Action<AUKCJA>(this.attach_AUKCJAs), new Action<AUKCJA>(this.detach_AUKCJAs));
			this._KATEGORIAs = new EntitySet<KATEGORIA>(new Action<KATEGORIA>(this.attach_KATEGORIAs), new Action<KATEGORIA>(this.detach_KATEGORIAs));
			this._KATEGORIA1 = default(EntityRef<KATEGORIA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kategoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_kategoria
		{
			get
			{
				return this._id_kategoria;
			}
			set
			{
				if ((this._id_kategoria != value))
				{
					this.Onid_kategoriaChanging(value);
					this.SendPropertyChanging();
					this._id_kategoria = value;
					this.SendPropertyChanged("id_kategoria");
					this.Onid_kategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rodzica", DbType="Int")]
		public System.Nullable<int> id_rodzica
		{
			get
			{
				return this._id_rodzica;
			}
			set
			{
				if ((this._id_rodzica != value))
				{
					if (this._KATEGORIA1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_rodzicaChanging(value);
					this.SendPropertyChanging();
					this._id_rodzica = value;
					this.SendPropertyChanged("id_rodzica");
					this.Onid_rodzicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_czy_lisc", DbType="Bit")]
		public System.Nullable<bool> czy_lisc
		{
			get
			{
				return this._czy_lisc;
			}
			set
			{
				if ((this._czy_lisc != value))
				{
					this.Onczy_liscChanging(value);
					this.SendPropertyChanging();
					this._czy_lisc = value;
					this.SendPropertyChanged("czy_lisc");
					this.Onczy_liscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KATEGORIA_AUKCJA", Storage="_AUKCJAs", ThisKey="id_kategoria", OtherKey="id_kategoria")]
		public EntitySet<AUKCJA> AUKCJAs
		{
			get
			{
				return this._AUKCJAs;
			}
			set
			{
				this._AUKCJAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KATEGORIA_KATEGORIA", Storage="_KATEGORIAs", ThisKey="id_kategoria", OtherKey="id_rodzica")]
		public EntitySet<KATEGORIA> KATEGORIAs
		{
			get
			{
				return this._KATEGORIAs;
			}
			set
			{
				this._KATEGORIAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KATEGORIA_KATEGORIA", Storage="_KATEGORIA1", ThisKey="id_rodzica", OtherKey="id_kategoria", IsForeignKey=true)]
		public KATEGORIA KATEGORIA1
		{
			get
			{
				return this._KATEGORIA1.Entity;
			}
			set
			{
				KATEGORIA previousValue = this._KATEGORIA1.Entity;
				if (((previousValue != value) 
							|| (this._KATEGORIA1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KATEGORIA1.Entity = null;
						previousValue.KATEGORIAs.Remove(this);
					}
					this._KATEGORIA1.Entity = value;
					if ((value != null))
					{
						value.KATEGORIAs.Add(this);
						this._id_rodzica = value.id_kategoria;
					}
					else
					{
						this._id_rodzica = default(Nullable<int>);
					}
					this.SendPropertyChanged("KATEGORIA1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AUKCJAs(AUKCJA entity)
		{
			this.SendPropertyChanging();
			entity.KATEGORIA = this;
		}
		
		private void detach_AUKCJAs(AUKCJA entity)
		{
			this.SendPropertyChanging();
			entity.KATEGORIA = null;
		}
		
		private void attach_KATEGORIAs(KATEGORIA entity)
		{
			this.SendPropertyChanging();
			entity.KATEGORIA1 = this;
		}
		
		private void detach_KATEGORIAs(KATEGORIA entity)
		{
			this.SendPropertyChanging();
			entity.KATEGORIA1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KLIENT")]
	public partial class KLIENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _login;
		
		private int _id_dane;
		
		private string _haslo;
		
		private System.DateTime _data_od;
		
		private System.Nullable<System.DateTime> _data_do;
		
		private EntitySet<OFERTA> _OFERTAs;
		
		private EntitySet<POWIADOMIENIE> _POWIADOMIENIEs;
		
		private EntityRef<DANE> _DANE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void Onid_daneChanging(int value);
    partial void Onid_daneChanged();
    partial void OnhasloChanging(string value);
    partial void OnhasloChanged();
    partial void Ondata_odChanging(System.DateTime value);
    partial void Ondata_odChanged();
    partial void Ondata_doChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_doChanged();
    #endregion
		
		public KLIENT()
		{
			this._OFERTAs = new EntitySet<OFERTA>(new Action<OFERTA>(this.attach_OFERTAs), new Action<OFERTA>(this.detach_OFERTAs));
			this._POWIADOMIENIEs = new EntitySet<POWIADOMIENIE>(new Action<POWIADOMIENIE>(this.attach_POWIADOMIENIEs), new Action<POWIADOMIENIE>(this.detach_POWIADOMIENIEs));
			this._DANE = default(EntityRef<DANE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dane", DbType="Int NOT NULL")]
		public int id_dane
		{
			get
			{
				return this._id_dane;
			}
			set
			{
				if ((this._id_dane != value))
				{
					if (this._DANE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_daneChanging(value);
					this.SendPropertyChanging();
					this._id_dane = value;
					this.SendPropertyChanged("id_dane");
					this.Onid_daneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haslo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string haslo
		{
			get
			{
				return this._haslo;
			}
			set
			{
				if ((this._haslo != value))
				{
					this.OnhasloChanging(value);
					this.SendPropertyChanging();
					this._haslo = value;
					this.SendPropertyChanged("haslo");
					this.OnhasloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_od", DbType="DateTime NOT NULL")]
		public System.DateTime data_od
		{
			get
			{
				return this._data_od;
			}
			set
			{
				if ((this._data_od != value))
				{
					this.Ondata_odChanging(value);
					this.SendPropertyChanging();
					this._data_od = value;
					this.SendPropertyChanged("data_od");
					this.Ondata_odChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_do", DbType="DateTime")]
		public System.Nullable<System.DateTime> data_do
		{
			get
			{
				return this._data_do;
			}
			set
			{
				if ((this._data_do != value))
				{
					this.Ondata_doChanging(value);
					this.SendPropertyChanging();
					this._data_do = value;
					this.SendPropertyChanged("data_do");
					this.Ondata_doChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KLIENT_OFERTA", Storage="_OFERTAs", ThisKey="login", OtherKey="login")]
		public EntitySet<OFERTA> OFERTAs
		{
			get
			{
				return this._OFERTAs;
			}
			set
			{
				this._OFERTAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KLIENT_POWIADOMIENIE", Storage="_POWIADOMIENIEs", ThisKey="login", OtherKey="login")]
		public EntitySet<POWIADOMIENIE> POWIADOMIENIEs
		{
			get
			{
				return this._POWIADOMIENIEs;
			}
			set
			{
				this._POWIADOMIENIEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANE_KLIENT", Storage="_DANE", ThisKey="id_dane", OtherKey="id_dane", IsForeignKey=true)]
		public DANE DANE
		{
			get
			{
				return this._DANE.Entity;
			}
			set
			{
				DANE previousValue = this._DANE.Entity;
				if (((previousValue != value) 
							|| (this._DANE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANE.Entity = null;
						previousValue.KLIENTs.Remove(this);
					}
					this._DANE.Entity = value;
					if ((value != null))
					{
						value.KLIENTs.Add(this);
						this._id_dane = value.id_dane;
					}
					else
					{
						this._id_dane = default(int);
					}
					this.SendPropertyChanged("DANE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OFERTAs(OFERTA entity)
		{
			this.SendPropertyChanging();
			entity.KLIENT = this;
		}
		
		private void detach_OFERTAs(OFERTA entity)
		{
			this.SendPropertyChanging();
			entity.KLIENT = null;
		}
		
		private void attach_POWIADOMIENIEs(POWIADOMIENIE entity)
		{
			this.SendPropertyChanging();
			entity.KLIENT = this;
		}
		
		private void detach_POWIADOMIENIEs(POWIADOMIENIE entity)
		{
			this.SendPropertyChanging();
			entity.KLIENT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OFERTA")]
	public partial class OFERTA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_oferta;
		
		private int _id_aukcji;
		
		private string _login;
		
		private decimal _kwota;
		
		private System.DateTime _data_zlozenia;
		
		private EntityRef<AUKCJA> _AUKCJA;
		
		private EntityRef<KLIENT> _KLIENT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ofertaChanging(int value);
    partial void Onid_ofertaChanged();
    partial void Onid_aukcjiChanging(int value);
    partial void Onid_aukcjiChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnkwotaChanging(decimal value);
    partial void OnkwotaChanged();
    partial void Ondata_zlozeniaChanging(System.DateTime value);
    partial void Ondata_zlozeniaChanged();
    #endregion
		
		public OFERTA()
		{
			this._AUKCJA = default(EntityRef<AUKCJA>);
			this._KLIENT = default(EntityRef<KLIENT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_oferta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_oferta
		{
			get
			{
				return this._id_oferta;
			}
			set
			{
				if ((this._id_oferta != value))
				{
					this.Onid_ofertaChanging(value);
					this.SendPropertyChanging();
					this._id_oferta = value;
					this.SendPropertyChanged("id_oferta");
					this.Onid_ofertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_aukcji", DbType="Int NOT NULL")]
		public int id_aukcji
		{
			get
			{
				return this._id_aukcji;
			}
			set
			{
				if ((this._id_aukcji != value))
				{
					if (this._AUKCJA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_aukcjiChanging(value);
					this.SendPropertyChanging();
					this._id_aukcji = value;
					this.SendPropertyChanged("id_aukcji");
					this.Onid_aukcjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					if (this._KLIENT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kwota", DbType="Money NOT NULL")]
		public decimal kwota
		{
			get
			{
				return this._kwota;
			}
			set
			{
				if ((this._kwota != value))
				{
					this.OnkwotaChanging(value);
					this.SendPropertyChanging();
					this._kwota = value;
					this.SendPropertyChanged("kwota");
					this.OnkwotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_zlozenia", DbType="DateTime NOT NULL")]
		public System.DateTime data_zlozenia
		{
			get
			{
				return this._data_zlozenia;
			}
			set
			{
				if ((this._data_zlozenia != value))
				{
					this.Ondata_zlozeniaChanging(value);
					this.SendPropertyChanging();
					this._data_zlozenia = value;
					this.SendPropertyChanged("data_zlozenia");
					this.Ondata_zlozeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AUKCJA_OFERTA", Storage="_AUKCJA", ThisKey="id_aukcji", OtherKey="id_aukcji", IsForeignKey=true)]
		public AUKCJA AUKCJA
		{
			get
			{
				return this._AUKCJA.Entity;
			}
			set
			{
				AUKCJA previousValue = this._AUKCJA.Entity;
				if (((previousValue != value) 
							|| (this._AUKCJA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AUKCJA.Entity = null;
						previousValue.OFERTAs.Remove(this);
					}
					this._AUKCJA.Entity = value;
					if ((value != null))
					{
						value.OFERTAs.Add(this);
						this._id_aukcji = value.id_aukcji;
					}
					else
					{
						this._id_aukcji = default(int);
					}
					this.SendPropertyChanged("AUKCJA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KLIENT_OFERTA", Storage="_KLIENT", ThisKey="login", OtherKey="login", IsForeignKey=true)]
		public KLIENT KLIENT
		{
			get
			{
				return this._KLIENT.Entity;
			}
			set
			{
				KLIENT previousValue = this._KLIENT.Entity;
				if (((previousValue != value) 
							|| (this._KLIENT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KLIENT.Entity = null;
						previousValue.OFERTAs.Remove(this);
					}
					this._KLIENT.Entity = value;
					if ((value != null))
					{
						value.OFERTAs.Add(this);
						this._login = value.login;
					}
					else
					{
						this._login = default(string);
					}
					this.SendPropertyChanged("KLIENT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.POWIADOMIENIE")]
	public partial class POWIADOMIENIE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _login;
		
		private string _tresc;
		
		private System.DateTime _data;
		
		private EntityRef<KLIENT> _KLIENT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OntrescChanging(string value);
    partial void OntrescChanged();
    partial void OndataChanging(System.DateTime value);
    partial void OndataChanged();
    #endregion
		
		public POWIADOMIENIE()
		{
			this._KLIENT = default(EntityRef<KLIENT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(20)")]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					if (this._KLIENT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tresc", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string tresc
		{
			get
			{
				return this._tresc;
			}
			set
			{
				if ((this._tresc != value))
				{
					this.OntrescChanging(value);
					this.SendPropertyChanging();
					this._tresc = value;
					this.SendPropertyChanged("tresc");
					this.OntrescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="Date NOT NULL")]
		public System.DateTime data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KLIENT_POWIADOMIENIE", Storage="_KLIENT", ThisKey="login", OtherKey="login", IsForeignKey=true)]
		public KLIENT KLIENT
		{
			get
			{
				return this._KLIENT.Entity;
			}
			set
			{
				KLIENT previousValue = this._KLIENT.Entity;
				if (((previousValue != value) 
							|| (this._KLIENT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KLIENT.Entity = null;
						previousValue.POWIADOMIENIEs.Remove(this);
					}
					this._KLIENT.Entity = value;
					if ((value != null))
					{
						value.POWIADOMIENIEs.Add(this);
						this._login = value.login;
					}
					else
					{
						this._login = default(string);
					}
					this.SendPropertyChanged("KLIENT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SPRZEDAWCA")]
	public partial class SPRZEDAWCA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _login;
		
		private int _id_dane;
		
		private string _haslo;
		
		private System.DateTime _data_od;
		
		private System.Nullable<System.DateTime> _data_do;
		
		private EntitySet<AUKCJA> _AUKCJAs;
		
		private EntityRef<DANE> _DANE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void Onid_daneChanging(int value);
    partial void Onid_daneChanged();
    partial void OnhasloChanging(string value);
    partial void OnhasloChanged();
    partial void Ondata_odChanging(System.DateTime value);
    partial void Ondata_odChanged();
    partial void Ondata_doChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_doChanged();
    #endregion
		
		public SPRZEDAWCA()
		{
			this._AUKCJAs = new EntitySet<AUKCJA>(new Action<AUKCJA>(this.attach_AUKCJAs), new Action<AUKCJA>(this.detach_AUKCJAs));
			this._DANE = default(EntityRef<DANE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dane", DbType="Int NOT NULL")]
		public int id_dane
		{
			get
			{
				return this._id_dane;
			}
			set
			{
				if ((this._id_dane != value))
				{
					if (this._DANE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_daneChanging(value);
					this.SendPropertyChanging();
					this._id_dane = value;
					this.SendPropertyChanged("id_dane");
					this.Onid_daneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haslo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string haslo
		{
			get
			{
				return this._haslo;
			}
			set
			{
				if ((this._haslo != value))
				{
					this.OnhasloChanging(value);
					this.SendPropertyChanging();
					this._haslo = value;
					this.SendPropertyChanged("haslo");
					this.OnhasloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_od", DbType="DateTime NOT NULL")]
		public System.DateTime data_od
		{
			get
			{
				return this._data_od;
			}
			set
			{
				if ((this._data_od != value))
				{
					this.Ondata_odChanging(value);
					this.SendPropertyChanging();
					this._data_od = value;
					this.SendPropertyChanged("data_od");
					this.Ondata_odChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_do", DbType="DateTime")]
		public System.Nullable<System.DateTime> data_do
		{
			get
			{
				return this._data_do;
			}
			set
			{
				if ((this._data_do != value))
				{
					this.Ondata_doChanging(value);
					this.SendPropertyChanging();
					this._data_do = value;
					this.SendPropertyChanged("data_do");
					this.Ondata_doChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SPRZEDAWCA_AUKCJA", Storage="_AUKCJAs", ThisKey="login", OtherKey="login")]
		public EntitySet<AUKCJA> AUKCJAs
		{
			get
			{
				return this._AUKCJAs;
			}
			set
			{
				this._AUKCJAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANE_SPRZEDAWCA", Storage="_DANE", ThisKey="id_dane", OtherKey="id_dane", IsForeignKey=true)]
		public DANE DANE
		{
			get
			{
				return this._DANE.Entity;
			}
			set
			{
				DANE previousValue = this._DANE.Entity;
				if (((previousValue != value) 
							|| (this._DANE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANE.Entity = null;
						previousValue.SPRZEDAWCAs.Remove(this);
					}
					this._DANE.Entity = value;
					if ((value != null))
					{
						value.SPRZEDAWCAs.Add(this);
						this._id_dane = value.id_dane;
					}
					else
					{
						this._id_dane = default(int);
					}
					this.SendPropertyChanged("DANE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AUKCJAs(AUKCJA entity)
		{
			this.SendPropertyChanging();
			entity.SPRZEDAWCA = this;
		}
		
		private void detach_AUKCJAs(AUKCJA entity)
		{
			this.SendPropertyChanging();
			entity.SPRZEDAWCA = null;
		}
	}
}
#pragma warning restore 1591
